# Generated by Django 4.0.3 on 2022-06-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matkul', '0003_remove_matakuliah_kelasmk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlahNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_absen', models.IntegerField()),
                ('nilai_tugas', models.IntegerField()),
                ('nilai_uts', models.IntegerField()),
                ('nilai_uas', models.IntegerField()),
                ('dataKelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matkul.kelas')),
            ],
        ),
    ]
