# Generated by Django 4.0.3 on 2022-06-16 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0004_alter_kelas_mahasiswa_alter_kelas_matkul'),
        ('olahnilai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olahnilai',
            name='dataMahasiswa',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='matkul.mahasiswa'),
            preserve_default=False,
        ),
    ]
