# Generated by Django 4.0.3 on 2022-06-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0005_alter_kelas_kelas_alter_kelas_matkul'),
        ('olahnilai', '0003_alter_olahnilai_datakelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olahnilai',
            name='dataKelas',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='matkul.kelas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='olahnilai',
            name='dataMahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matkul.mahasiswa'),
        ),
    ]
