# Generated by Django 4.0.3 on 2022-06-15 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=4, verbose_name='Kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField(max_length=14)),
                ('nama', models.CharField(max_length=255)),
                ('prodi', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mataKuliah', models.CharField(max_length=60, verbose_name='Mata Kuliah')),
                ('dosen_pengajar', models.CharField(max_length=255, verbose_name='Dosen Pengajar')),
                ('kelasMK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matkul.kelas')),
                ('mahasiswa', models.ManyToManyField(blank=True, null=True, to='matkul.mahasiswa')),
            ],
        ),
    ]
