# Generated by Django 4.0.3 on 2022-06-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=14),
        ),
    ]
