# Generated by Django 4.0.3 on 2022-06-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0002_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='kelasMK',
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='mahasiswa',
        ),
        migrations.AddField(
            model_name='kelas',
            name='mahasiswa',
            field=models.ManyToManyField(blank=True, null=True, to='matkul.mahasiswa'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='matkul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matkul.matakuliah'),
        ),
    ]
