# Generated by Django 4.0.3 on 2022-06-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0003_remove_matakuliah_kelasmk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='mahasiswa',
            field=models.ManyToManyField(to='matkul.mahasiswa'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matkul.matakuliah'),
        ),
    ]
